{
  imports = [
    ./argocd.nix
    ./aws.nix
    ./env.nix
    ./git.nix
    ./home-manager.nix
    ./lazygit.nix
    ./nix-tools.nix
    ./nvim.nix
    ./pulsemixer.nix
    ./opencode.nix
    ./productivity.nix
    ./ranger.nix
    ./udiskie.nix
    ./utils.nix
    ./vault.nix
    ./x11.nix
    ./zsh.nix
  ];
}
