# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "nvme" "usb_storage" "sd_mod" "sr_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/27cf5e41-c42f-4bde-9e90-19fd0cef0ad3";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-cda3107a-9ea0-4860-a484-9b71b026f381".device = "/dev/disk/by-uuid/cda3107a-9ea0-4860-a484-9b71b026f381";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/68AC-F01B";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  fileSystems."/mnt/nas" = {
    device = "192.168.1.251:/mnt/zfs_pool/user";
    fsType = "nfs";
    options = [ "x-systemd.automount" "noauto" ];
  };

  #swapDevices =
  #  [ { device = "/dev/disk/by-uuid/1823b55d-3293-474b-a984-0739918b5869"; }
  #  ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp0s31f6.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp146s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
